databases:
  - name: todoapidb
    plan: free
    databaseName: todoapi
    user: todoapi

services:
  - type: web
    plan: free
    name: todoapi
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'gunicorn todoapi.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todoapidb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: api.settings
