databases:
  - name: apidb
    plan: free
    databaseName: api
    user: api

services:
  - type: web
    plan: free
    name: api
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'gunicorn api.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: apidb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: api.settings
