# Generated by Django 3.1.6 on 2021-02-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_auto_20210202_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(default='2021-10-10'),
            preserve_default=False,
        ),
    ]
